spring:
  mvc:
    view:
      suffix: .html
      prefix: /resources/templates
  data:
    mongodb:
      database: feature_toggle
      username: g.ruzavin
      password: secret
      port: 27017
      uri: mongodb://localhost:27017/feature_toggle
    redis:
      client-type: lettuce
